#!/bin/bash
echo "🚀 Swagger Documentation Setup Complete!"
echo ""
echo "📋 What was added:"
echo "  ✅ swagger-jsdoc and swagger-ui-express packages"
echo "  ✅ Swagger configuration in src/config/swagger.ts"
echo "  ✅ Swagger middleware in server.ts"
echo "  ✅ Example documentation in auth routes"
echo ""
echo "🌐 Access your API documentation at:"
echo "  http://localhost:3002/api-docs"
echo ""
echo "📝 To add documentation to other routes, use JSDoc comments like:"
echo "/**"
echo " * @swagger"
echo " * /api/your-endpoint:"
echo " *   get:"
echo " *     summary: Your endpoint description"
echo " *     tags: [YourTag]"
echo " */"
echo ""
echo "🔧 Start your server with: npm run dev"