#!/bin/bash
echo "🎉 Complete Swagger Documentation Added!"
echo ""
echo "📚 All API Routes Documented:"
echo ""
echo "🔐 Authentication (Customer/Salon Owner/Admin)"
echo "  ✅ POST /api/auth/register - Register new user"
echo "  ✅ POST /api/auth/login - User login"
echo "  ✅ GET /api/auth/me - Get current user profile"
echo ""
echo "👤 Users (Customer)"
echo "  ✅ GET /api/users/profile - Get user profile"
echo "  ✅ PUT /api/users/profile - Update user profile"
echo ""
echo "🏪 Salons (Customer/Salon Owner/Admin)"
echo "  ✅ GET /api/salons - Get all salons"
echo "  ✅ POST /api/salons - Create salon (Salon Owner/Admin)"
echo "  ✅ GET /api/salons/search - Search salons"
echo "  ✅ GET /api/salons/{id} - Get salon details"
echo "  ✅ PUT /api/salons/{id} - Update salon (Salon Owner/Admin)"
echo "  ✅ DELETE /api/salons/{id} - Delete salon (Salon Owner/Admin)"
echo "  ✅ GET /api/salons/{id}/services - Get salon services"
echo ""
echo "💼 Services (Customer/Salon Owner)"
echo "  ✅ GET /api/services - Get all services"
echo "  ✅ POST /api/services - Create service (Salon Owner)"
echo ""
echo "📅 Bookings (Customer)"
echo "  ✅ GET /api/bookings - Get user bookings"
echo "  ✅ POST /api/bookings - Create booking"
echo "  ✅ PUT /api/bookings/{id}/cancel - Cancel booking"
echo "  ✅ PUT /api/bookings/{id}/reschedule - Reschedule booking"
echo ""
echo "📋 Appointments (Customer)"
echo "  ✅ POST /api/appointments/request - Request appointment"
echo "  ✅ GET /api/appointments/upcoming - Get upcoming appointments"
echo "  ✅ GET /api/appointments/{id}/status - Get appointment status"
echo ""
echo "💳 Payments (Customer)"
echo "  ✅ POST /api/payments - Create payment"
echo "  ✅ GET /api/payments - Get payment history"
echo ""
echo "📱 OTP (All Users)"
echo "  ✅ POST /api/otp/send - Send OTP"
echo "  ✅ POST /api/otp/verify - Verify OTP"
echo ""
echo "⏰ Availability (Customer)"
echo "  ✅ GET /api/availability/slots - Get available time slots"
echo ""
echo "📍 Location (Customer)"
echo "  ✅ GET /api/location/nearest - Get nearest salons"
echo "  ✅ PUT /api/location/update - Update user location"
echo ""
echo "📤 Upload (Customer/Salon Owner)"
echo "  ✅ POST /api/upload/avatar - Upload user avatar"
echo "  ✅ POST /api/upload/salon-images - Upload salon images"
echo ""
echo "👨‍💼 Salon Owner (Salon Owner Only)"
echo "  ✅ GET /api/salon-owner/salons - Get my salons"
echo "  ✅ GET /api/salon-owner/salons/{id}/bookings - Get salon bookings"
echo "  ✅ GET /api/salon-owner/salons/{id}/stats - Get salon statistics"
echo "  ✅ PUT /api/salon-owner/bookings/{id}/status - Update booking status"
echo ""
echo "🔧 Admin (Admin Only)"
echo "  ✅ GET /api/admin/users - Get all users"
echo "  ✅ GET /api/admin/salon-owners - Get salon owners"
echo "  ✅ PUT /api/admin/users/{id}/role - Update user role"
echo "  ✅ DELETE /api/admin/users/{id} - Delete user"
echo "  ✅ GET /api/admin/salons - Get all salons"
echo "  ✅ PUT /api/admin/salons/{id}/status - Update salon status"
echo ""
echo "🔑 Features Added:"
echo "  ✅ JWT Bearer Authentication"
echo "  ✅ Role-based access control (Customer/Salon Owner/Admin)"
echo "  ✅ Complete request/response schemas"
echo "  ✅ Parameter validation"
echo "  ✅ Error response documentation"
echo "  ✅ File upload documentation"
echo ""
echo "🌐 Access your complete API documentation at:"
echo "  http://localhost:3002/api-docs"
echo ""
echo "🚀 Start your server: npm run dev"